@startuml

'==========================================================
'                 TABLAS PRINCIPALES
'==========================================================

class Lead {
    +id: Integer
    +created_at: DateTime
    +updated_at: DateTime
    +campaign_id: Integer
    +field_values: List<LeadFieldValue>
}

class LeadField {
    +id: Integer
    +name: String
    +field_type_code: Integer
    +required: Boolean
    +default_value: String
    +is_primary: Boolean
    +input_mask: String
    +order: Integer
    +campaign_id: Integer
    +field_values: List<LeadFieldValue>
    +nomenclator_id (nullable)
    +validation_rules: List<ValidationRule>
}

class FileType{
    +id
    +name (image, pdf, document, etc.)
}

class LeadFieldValue {
    +id: Integer
    +lead_id: Integer
    +field_id: Integer
    +value: String
}

class LeadFieldType {
    +id: Integer
    +name: String
    +data_type: Enum

}

'==========================================================
'        VALIDACIONES CONFIGURADAS POR EL USUARIO
'==========================================================

class ValidationRule {
    +id: Integer
    +name: String
    +expression: String
    +error_message: String
    +template_code: String
    +template_params: String
    +field: LeadField
}
'==========================
' GRUPOS / SEGMENTOS
'==========================

class Campaign {
    +id: Integer
    +name: String
    +description: String?
    +parent_Campaign_id: Integer?
    +workspace_id: Integer
    +leads: List<Lead>
    +nomenclators: List<Nomenclator>
}

class Workspace {
    +id: Integer
    +name: String
    +description: String?
    +campaigns: List<Campaign>
}


'==========================================================
'                          NOMENCLADORES
'==========================================================

class Nomenclator{
    +id: Integer
    +name: String
    +description: String
    +campaign: Campaign
    +parent_nomenclator: Nomenclator
}

class NomenclatorItem{
    +id: Integer
    +code: String
    +value: String
    +parent_item_id: Integer
    +nomenclator_id: Integer
}


'==========================================================
'                          RELACIONES
'==========================================================

LeadFieldValue "*" <--> "1" Lead
LeadFieldValue "*" --> "1" LeadField
LeadField "1" --> "1" LeadFieldType
LeadField --> "0..1" FileType : tiene >
LeadFieldValue "*" --> "1" NomenclatorItem

' ValidationRule relations
ValidationRule "*" --> "1" LeadField : valida >

' explicit membership class relations
Lead "*" --> "1" Campaign
Campaign "1" <-- "*" LeadField : define >
Campaign "*" --> "1" Workspace

' Nomenclator relations
LeadField "*" --> "0..1" Nomenclator : usa >
NomenclatorItem "*" --> "1" Nomenclator : pertenece_a >
Nomenclator "*" --> "1" Campaign : para >
Nomenclator --> Nomenclator : pertenece
NomenclatorItem --> NomenclatorItem : pertenece



@enduml
